---
- name: Provision all nodes
  hosts: redis
  become: true
  vars_files:
    - ../group_vars/redis-cluster.yml
  roles:
    - common

- name: Install Redis
  hosts: redis
  become: true
  vars_files:
    - ../group_vars/redis-cluster.yml
  roles:
    - installation